import Head from 'next/head'

const Index = () => {
  return (
    <div>
      <Head>
        <title>My app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Home page
    </div>
  )
}

export default Index