import Head from 'next/head'
import axios from 'axios'
import { splitContentByType } from '../utils/content-utils'
import { getContent } from '../modules/contentful/content'

const Index = ({ content }) => {
  return (
    <div>
      <Head>
        <title>My app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Home page
    </div>
  )
}

export const getStaticProps = async () => {
  const content = await getContent()
  // const splitContent = splitContentByType(content)
  return {
    props: { 'content': JSON.stringify(content) },
  }
}

export default Index